name: 🚀 Python Package Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  release-build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    env:
      PYTHON_VERSION: '3.10'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Build Metadata
        id: meta
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "TRIGGERED_BY=manual" >> $GITHUB_ENV
            echo "BUILD_TYPE=manual" >> $GITHUB_OUTPUT
          else
            echo "TRIGGERED_BY=release" >> $GITHUB_ENV
            echo "BUILD_TYPE=release" >> $GITHUB_OUTPUT
          fi
          echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry --version

      - name: Configure Dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Build Package
        run: |
          poetry build

      - name: Display Artifacts Summary
        run: |
          echo "## Package Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "* **Version**: $(poetry version -s)" >> $GITHUB_STEP_SUMMARY
          echo "* **Build Timestamp**: $TIMESTAMP" >> $GITHUB_STEP_SUMMARY
          echo "* **Trigger**: $TRIGGERED_BY" >> $GITHUB_STEP_SUMMARY

          if [ -d "dist" ]; then
            echo "* **Files**:" >> $GITHUB_STEP_SUMMARY
            for file in dist/*; do
              size=$(du -h "$file" | cut -f1)
              echo "  - $(basename "$file") ($size)" >> $GITHUB_STEP_SUMMARY
            done
          else
            echo "* **Files**: None found" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Distribution Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-distribution
          path: dist/

